// 교육부 지정 초등영단어 800개 - 카테고리별 그룹화
const wordGroups = {
    "동물": [
        {word: "animal", meaning: "동물"}, {word: "cat", meaning: "고양이"}, {word: "dog", meaning: "개"}, 
        {word: "bird", meaning: "새"}, {word: "fish", meaning: "고기/낚시하다"}, {word: "bear", meaning: "곰"}, 
        {word: "chicken", meaning: "닭"}, {word: "cow", meaning: "암소"}, {word: "duck", meaning: "오리"}, 
        {word: "hen", meaning: "암닭"}, {word: "horse", meaning: "말"}, {word: "lion", meaning: "사자"}, 
        {word: "monkey", meaning: "원숭이"}, {word: "pig", meaning: "돼지"}, {word: "sheep", meaning: "양"}, 
        {word: "tiger", meaning: "호랑이"}, {word: "dolphin", meaning: "돌고래"}, {word: "elephant", meaning: "코끼리"}, 
        {word: "giraffe", meaning: "기린"}, {word: "kangaroo", meaning: "캥거루"}, {word: "panda", meaning: "판다"}, 
        {word: "rabbit", meaning: "토끼"}, {word: "snake", meaning: "뱀"}, {word: "turtle", meaning: "거북이"}, 
        {word: "whale", meaning: "고래"}, {word: "wolf", meaning: "늑대"}, {word: "zebra", meaning: "얼룩말"}, 
        {word: "deer", meaning: "사슴"}, {word: "fox", meaning: "여우"}, {word: "frog", meaning: "개구리"}, 
        {word: "goat", meaning: "염소"}, {word: "hippo", meaning: "하마"}, {word: "mouse", meaning: "쥐"}, 
        {word: "penguin", meaning: "펭귄"}, {word: "shark", meaning: "상어"}, {word: "spider", meaning: "거미"}
    ],
    "음식": [
        {word: "apple", meaning: "사과"}, {word: "banana", meaning: "바나나"}, {word: "bread", meaning: "빵"}, 
        {word: "breakfast", meaning: "아침"}, {word: "butter", meaning: "버터"}, {word: "cake", meaning: "케이크"}, 
        {word: "candy", meaning: "사탕"}, {word: "cheese", meaning: "치즈"}, {word: "coffee", meaning: "커피"}, 
        {word: "cream", meaning: "크림"}, {word: "dinner", meaning: "저녁"}, {word: "egg", meaning: "계란"}, 
        {word: "food", meaning: "음식"}, {word: "fruit", meaning: "과일"}, {word: "grape", meaning: "포도"}, 
        {word: "hamburger", meaning: "햄버거"}, {word: "juice", meaning: "주스"}, {word: "lunch", meaning: "점심식사"}, 
        {word: "meat", meaning: "고기"}, {word: "melon", meaning: "멜론"}, {word: "milk", meaning: "우유"}, 
        {word: "orange", meaning: "오렌지"}, {word: "pear", meaning: "배"}, {word: "rice", meaning: "쌀"}, 
        {word: "salad", meaning: "샐러드"}, {word: "salt", meaning: "소금"}, {word: "soup", meaning: "스프"}, 
        {word: "strawberry", meaning: "딸기"}, {word: "sugar", meaning: "설탕"}, {word: "supper", meaning: "저녁식사"}, 
        {word: "tea", meaning: "차"}, {word: "tomato", meaning: "토마토"}, {word: "vegetable", meaning: "야채"}, 
        {word: "water", meaning: "물"}, {word: "pizza", meaning: "피자"}, {word: "sandwich", meaning: "샌드위치"}
    ],
    "신체": [
        {word: "arm", meaning: "팔"}, {word: "back", meaning: "뒤에"}, {word: "body", meaning: "몸"}, 
        {word: "ear", meaning: "귀"}, {word: "eye", meaning: "눈"}, {word: "face", meaning: "얼굴"}, 
        {word: "finger", meaning: "손가락"}, {word: "foot", meaning: "발"}, {word: "hair", meaning: "머리카락"}, 
        {word: "hand", meaning: "손"}, {word: "head", meaning: "머리"}, {word: "heart", meaning: "마음/상징"}, 
        {word: "knee", meaning: "무릎"}, {word: "leg", meaning: "다리"}, {word: "lip", meaning: "입술"}, 
        {word: "mouth", meaning: "입"}, {word: "neck", meaning: "목"}, {word: "nose", meaning: "코"}, 
        {word: "shoulder", meaning: "어깨"}, {word: "tooth", meaning: "이"}, {word: "brain", meaning: "뇌"}, 
        {word: "chest", meaning: "가슴"}, {word: "elbow", meaning: "팔꿈치"}, {word: "stomach", meaning: "배"}, 
        {word: "throat", meaning: "목"}, {word: "thumb", meaning: "엄지"}, {word: "toe", meaning: "발가락"}, 
        {word: "tongue", meaning: "혀"}, {word: "wrist", meaning: "손목"}, {word: "ankle", meaning: "발목"}
    ],
    "학용품": [
        {word: "book", meaning: "책"}, {word: "pen", meaning: "펜/만년필"}, {word: "pencil", meaning: "연필"}, 
        {word: "desk", meaning: "책상"}, {word: "bag", meaning: "가방"}, {word: "eraser", meaning: "지우개"}, 
        {word: "paper", meaning: "종이"}, {word: "ruler", meaning: "자"}, {word: "chalk", meaning: "분필"}, 
        {word: "crayon", meaning: "크레옹"}, {word: "dictionary", meaning: "사전"}, {word: "diary", meaning: "일기"}, 
        {word: "lesson", meaning: "학과"}, {word: "library", meaning: "도서관"}, {word: "note", meaning: "공책"}, 
        {word: "page", meaning: "쪽"}, {word: "school", meaning: "학교"}, {word: "student", meaning: "학생"}, 
        {word: "teacher", meaning: "가르치다"}, {word: "class", meaning: "학급"}, {word: "classmate", meaning: "동급생"}, 
        {word: "homework", meaning: "숙제"}, {word: "test", meaning: "시험"}, {word: "study", meaning: "공부하다"}, 
        {word: "learn", meaning: "배우다"}, {word: "read", meaning: "읽다"}, {word: "write", meaning: "쓰다"}, 
        {word: "listen", meaning: "듣다"}, {word: "speak", meaning: "이야기하다"}, {word: "computer", meaning: "컴퓨터"}
    ],
    "색깔": [
        {word: "black", meaning: "검정색"}, {word: "blue", meaning: "푸른"}, {word: "brown", meaning: "갈색"}, 
        {word: "color", meaning: "색깔"}, {word: "gray", meaning: "회색"}, {word: "green", meaning: "녹색"}, 
        {word: "orange", meaning: "오렌지"}, {word: "pink", meaning: "분홍"}, {word: "red", meaning: "빨강"}, 
        {word: "white", meaning: "하얀색"}, {word: "yellow", meaning: "노랑색"}, {word: "bright", meaning: "밝은"}, 
        {word: "dark", meaning: "어두운"}, {word: "light", meaning: "빛"}, {word: "rainbow", meaning: "무지개"}, 
        {word: "gold", meaning: "금"}, {word: "silver", meaning: "은"}, {word: "purple", meaning: "보라색"}, 
        {word: "violet", meaning: "보라색"}, {word: "navy", meaning: "네이비"}, {word: "cream", meaning: "크림색"}
    ],
    "가족": [
        {word: "family", meaning: "가족"}, {word: "mother", meaning: "어머니"}, {word: "father", meaning: "아버지"}, 
        {word: "baby", meaning: "아기"}, {word: "brother", meaning: "형제"}, {word: "sister", meaning: "자매"}, 
        {word: "son", meaning: "아들"}, {word: "daughter", meaning: "딸"}, {word: "aunt", meaning: "이모,고모"}, 
        {word: "uncle", meaning: "삼촌"}, {word: "cousin", meaning: "사촌"}, {word: "grandmother", meaning: "할머니"}, 
        {word: "grandfather", meaning: "할아버지"}, {word: "parent", meaning: "부모"}, {word: "child", meaning: "어린이"}, 
        {word: "boy", meaning: "소년"}, {word: "girl", meaning: "소녀"}, {word: "man", meaning: "사람/남자"}, 
        {word: "woman", meaning: "여자"}, {word: "people", meaning: "사람"}, {word: "friend", meaning: "친구"}, 
        {word: "kid", meaning: "아이"}, {word: "lady", meaning: "숙녀"}, {word: "daddy", meaning: "아빠/아버지"}, 
        {word: "mommy", meaning: "엄마"}, {word: "husband", meaning: "남편"}, {word: "wife", meaning: "아내"}
    ],
    "집과 물건": [
        {word: "house", meaning: "집"}, {word: "home", meaning: "집"}, {word: "room", meaning: "방"}, 
        {word: "door", meaning: "문"}, {word: "window", meaning: "창문"}, {word: "wall", meaning: "벽"}, 
        {word: "floor", meaning: "마루"}, {word: "ceiling", meaning: "천장"}, {word: "chair", meaning: "의자"}, 
        {word: "table", meaning: "식탁/탁자"}, {word: "bed", meaning: "침대"}, {word: "kitchen", meaning: "부엌"}, 
        {word: "box", meaning: "상자"}, {word: "bottle", meaning: "병"}, {word: "bowl", meaning: "사발"}, 
        {word: "cup", meaning: "컵"}, {word: "plate", meaning: "접시"}, {word: "spoon", meaning: "숟가락"}, 
        {word: "fork", meaning: "포크"}, {word: "knife", meaning: "칼"}, {word: "basket", meaning: "바구니"}, 
        {word: "clock", meaning: "시계"}, {word: "lamp", meaning: "등불"}, {word: "mirror", meaning: "거울"}, 
        {word: "picture", meaning: "그림"}, {word: "toy", meaning: "인형"}, {word: "doll", meaning: "인형"}, 
        {word: "ball", meaning: "공"}, {word: "balloon", meaning: "풍선"}, {word: "curtain", meaning: "커튼"}
    ],
    "옷과 신발": [
        {word: "clothes", meaning: "옷"}, {word: "shirt", meaning: "셔츠"}, {word: "dress", meaning: "드레스"}, 
        {word: "pants", meaning: "바지"}, {word: "skirt", meaning: "치마"}, {word: "coat", meaning: "코트"}, 
        {word: "jacket", meaning: "재킷"}, {word: "sweater", meaning: "스웨터"}, {word: "hat", meaning: "모자"}, 
        {word: "cap", meaning: "모자"}, {word: "shoe", meaning: "구두"}, {word: "sock", meaning: "양말"}, 
        {word: "glove", meaning: "장갑"}, {word: "belt", meaning: "벨트"}, {word: "tie", meaning: "매다"}, 
        {word: "button", meaning: "단추"}, {word: "pocket", meaning: "주머니"}, {word: "uniform", meaning: "제복"}, 
        {word: "pajamas", meaning: "잠옷"}, {word: "underwear", meaning: "속옷"}, {word: "scarf", meaning: "스카프"}
    ],
    "A단어": [
        {word: "a", meaning: "하나의"}, {word: "about", meaning: "~에 대하여, 대략~, 약~"}, 
        {word: "across", meaning: "~을 가로질러, ~을 건너서"}, {word: "act", meaning: "행동하다, 행동, 행위"}, 
        {word: "actor", meaning: "영화배우"}, {word: "address", meaning: "주소, 연설"}, 
        {word: "afraid", meaning: "무서워하여, 두려워하여"}, {word: "after", meaning: "~뒤에, ~다음에"}, 
        {word: "afternoon", meaning: "오후"}, {word: "again", meaning: "또, 다시 한 번"}, 
        {word: "age", meaning: "나이, 연령"}, {word: "ago", meaning: "~전에"}, 
        {word: "air", meaning: "공기, 공중"}, {word: "airplane", meaning: "비행기"}, 
        {word: "airport", meaning: "공항, 비행장"}, {word: "album", meaning: "앨범, 사진첩"}, 
        {word: "all", meaning: "모든, 모두, 전부"}, {word: "along", meaning: "~을 따라서"}, 
        {word: "always", meaning: "항상, 언제나"}, {word: "among", meaning: "~사이에, ~가운데"}, 
        {word: "an", meaning: "하나의"}, {word: "and", meaning: "그리고, ~와"}, 
        {word: "angry", meaning: "화난, 성난"}, {word: "answer", meaning: "대답, 대답하다"}, 
        {word: "any", meaning: "어떤, 무슨, 무언가"}, {word: "apartment", meaning: "아파트"}, 
        {word: "around", meaning: "~주위에, ~둘레에"}, {word: "arrive", meaning: "도착하다"}, 
        {word: "as", meaning: "~만큼, ~할 때, ~하면서, ~로서"}, {word: "ask", meaning: "묻다, 질문하다"}, 
        {word: "at", meaning: "~때에(시간), ~에서(장소)"}, {word: "autumn", meaning: "가을"}, 
        {word: "away", meaning: "멀리, 떨어져서, 저쪽에, ~에 없는"}
    ],
    "B단어": [
        {word: "back", meaning: "뒤, 등, 돌아오다"}, {word: "bad", meaning: "(행동이) 나쁜, 옳지 않은, (음식 등이)상한, 서투른"}, 
        {word: "band", meaning: "밴드, 악단"}, {word: "bank", meaning: "은행"}, 
        {word: "base", meaning: "바닥, 밑면, (야구의)베이스, 루"}, {word: "bath", meaning: "목욕"}, 
        {word: "be", meaning: "~이다, ~이 되다"}, {word: "beach", meaning: "해변, 바닷가"}, 
        {word: "beautiful", meaning: "아름다운, 예쁜"}, {word: "because", meaning: "왜냐하면, ~이기 때문에"}, 
        {word: "become", meaning: "~이 되다"}, {word: "before", meaning: "~앞에, ~전에"}, 
        {word: "begin", meaning: "시작하다"}, {word: "behind", meaning: "~뒤에"}, 
        {word: "bell", meaning: "종, 방울, 종소리"}, {word: "below", meaning: "~의 밑에, ~의 아래에"}, 
        {word: "bench", meaning: "벤치, 긴 의자"}, {word: "beside", meaning: "~의 옆에"}, 
        {word: "between", meaning: "~의 사이에"}, {word: "bicycle", meaning: "자전거"}, 
        {word: "big", meaning: "큰, 커다란"}, {word: "birthday", meaning: "생일"}, 
        {word: "blank", meaning: "비어있는"}, {word: "blow", meaning: "(바람이)불다, (입으로)불다"}, 
        {word: "board", meaning: "널빤지, 판자, 판"}, {word: "boat", meaning: "보트, 작은 배"}, 
        {word: "break", meaning: "깨다, 부수다"}, {word: "bridge", meaning: "다리, 교량"}, 
        {word: "bring", meaning: "가져오다, 데려오다"}, {word: "brush", meaning: "솔"}, 
        {word: "build", meaning: "짓다, 세우다"}, {word: "burn", meaning: "타다, 불타다, 태우다, (불에 덴) 상처, 화상"}, 
        {word: "burnt", meaning: "burn의 과거, 과거분사형"}, {word: "bus", meaning: "버스"}, 
        {word: "busy", meaning: "바쁜"}, {word: "but", meaning: "그러나, 그렇지만"}, 
        {word: "buy", meaning: "사다"}, {word: "by", meaning: "~의 옆에"}, 
        {word: "bye", meaning: "잘까요, 안녕(헤어질 때 하는 인사말)"}
    ],
    "C단어": [
        {word: "calendar", meaning: "달력"}, {word: "call", meaning: "~를 부르다, 전화하다, (잠시)들르다"}, 
        {word: "camera", meaning: "카메라, 사진기"}, {word: "camp", meaning: "야영하다, 캠프하다"}, 
        {word: "can", meaning: "~할 수 있다"}, {word: "candle", meaning: "양초"}, 
        {word: "capital", meaning: "수도"}, {word: "captain", meaning: "선장"}, 
        {word: "care", meaning: "주의, 조심"}, {word: "carpenter", meaning: "목공"}, 
        {word: "carry", meaning: "~을 나르다, ~을 가지고 있다"}, {word: "cartoon", meaning: "만화"}, 
        {word: "case", meaning: "상자"}, {word: "cassette", meaning: "카세트테이프"}, 
        {word: "catch", meaning: "잡다"}, {word: "center", meaning: "중심, 중앙"}, 
        {word: "chance", meaning: "기회"}, {word: "change", meaning: "변화다, 바꾸다, 변경, 변화, 거스름돈, 잔돈"}, 
        {word: "cheap", meaning: "값싼"}, {word: "chopstick", meaning: "젓가락"}, 
        {word: "church", meaning: "교회"}, {word: "circle", meaning: "원"}, 
        {word: "city", meaning: "도시"}, {word: "clean", meaning: "깨끗한, 청결한"}, 
        {word: "climb", meaning: "(나무, 산 등에) 오르다"}, {word: "close", meaning: "닫다"}, 
        {word: "cloud", meaning: "구름"}, {word: "club", meaning: "클럽, 모임"}, 
        {word: "coin", meaning: "동전"}, {word: "cold", meaning: "추운, 차가운"}, 
        {word: "come", meaning: "오다"}, {word: "cook", meaning: "요리사"}, 
        {word: "cool", meaning: "시원한, 서늘한"}, {word: "copy", meaning: "그대로 옮겨 쓰다"}, 
        {word: "corner", meaning: "구석, 모퉁이"}, {word: "count", meaning: "세다"}, 
        {word: "country", meaning: "나라, 국가, 시골"}, {word: "course", meaning: "과목, 경로"}, 
        {word: "cover", meaning: "가리다, 덮다"}, {word: "cross", meaning: "(길 따위를) 건너다"}, 
        {word: "cry", meaning: "울다, 외치다"}, {word: "cut", meaning: "자르다"}, 
        {word: "cute", meaning: "귀여운"}
    ],
    "D단어": [
        {word: "dad", meaning: "아빠"}, {word: "dance", meaning: "춤추다"}, 
        {word: "danger", meaning: "위험, 위독한 상태"}, {word: "dark", meaning: "캄캄한, 어두운"}, 
        {word: "date", meaning: "날짜"}, {word: "day", meaning: "낮, 하루, ~일"}, 
        {word: "dead", meaning: "(죽은 듯이)조용한, 죽은"}, {word: "deep", meaning: "깊은, 깊숙이 들어간"}, 
        {word: "dial", meaning: "전화 걸다, 다이얼을 돌리다"}, {word: "die", meaning: "죽다, 사망하다"}, 
        {word: "dirty", meaning: "더러운"}, {word: "dish", meaning: "접시"}, 
        {word: "do", meaning: "~을 하다, 행하다, 의문문.부정문의 조동사"}, {word: "doctor", meaning: "의사"}, 
        {word: "dollar", meaning: "달러(미국의 화폐단위)"}, {word: "down", meaning: "아래로, 낮은 곳으로"}, 
        {word: "draw", meaning: "~을 그리다, 끌다, 끌어당기다"}, {word: "dream", meaning: "꿈"}, 
        {word: "drink", meaning: "(물이나 음료 등을) 마시다"}, {word: "drive", meaning: "운전하다"}, 
        {word: "drop", meaning: "방울, 물방울, ~을 떨어뜨리다"}, {word: "drum", meaning: "북, 드럼"}, 
        {word: "dry", meaning: "마른, 건조한"}
    ],
    "E단어": [
        {word: "early", meaning: "일찍"}, {word: "earth", meaning: "지구, 땅"}, 
        {word: "east", meaning: "동쪽"}, {word: "echo", meaning: "메아리"}, 
        {word: "empty", meaning: "빈, 비어있는"}, {word: "end", meaning: "끝, 마지막"}, 
        {word: "engine", meaning: "(기계의)엔진"}, {word: "enjoy", meaning: "~을 즐기다"}, 
        {word: "enough", meaning: "충분히, ~할 만큼"}, {word: "evening", meaning: "저녁, 밤"}, 
        {word: "every", meaning: "매~, 모든"}, {word: "example", meaning: "보기, 사례"}, 
        {word: "excellent", meaning: "뛰어난, 우수한"}, {word: "excite", meaning: "흥분시키다, 자극하다"}, 
        {word: "excuse", meaning: "용서하다, 변명"}, {word: "exercise", meaning: "운동"}
    ],
    "F단어": [
        {word: "fact", meaning: "사실, 진실"}, {word: "fair", meaning: "공평한, 공정한"}, 
        {word: "fall", meaning: "떨어지다, 넘어지다, 가을"}, {word: "famous", meaning: "유명한"}, 
        {word: "far", meaning: "멀리, 멀리 떨어져"}, {word: "farm", meaning: "농장, 목장"}, 
        {word: "fast", meaning: "빠른"}, {word: "fat", meaning: "뚱뚱한, 살찐"}, 
        {word: "feel", meaning: "~을 느끼다"}, {word: "few", meaning: "거의 없는"}, 
        {word: "field", meaning: "밭, 들판, 경기장"}, {word: "fight", meaning: "싸우다"}, 
        {word: "fill", meaning: "~을 채우다"}, {word: "film", meaning: "필름, 영화"}, 
        {word: "find", meaning: "~을 발견하다, ~을 찾다"}, {word: "fine", meaning: "좋은, 훌륭한"}, 
        {word: "finish", meaning: "~을 끝내다"}, {word: "fire", meaning: "불, 화재"}, 
        {word: "fix", meaning: "고치다, 가다듬다, (시간.장소 등을)정하다, ~에 달고, 고정 시키다"}, 
        {word: "flag", meaning: "기, 깃발"}, {word: "flower", meaning: "꽃"}, 
        {word: "fly", meaning: "날다, ~을 날리다"}, {word: "follow", meaning: "~을 따르다, ~을 따라가다(따라오다)"}, 
        {word: "fool", meaning: "바보"}, {word: "for", meaning: "~동안, ~을 위해"}, 
        {word: "forget", meaning: "~을 잊다"}, {word: "free", meaning: "무료로 주는, 한가한, 여유 있는"}, 
        {word: "fresh", meaning: "신선한, 새로운"}, {word: "from", meaning: "~에서, ~로부터"}, 
        {word: "front", meaning: "앞"}, {word: "full", meaning: "가득 찬, 가득한"}, 
        {word: "fun", meaning: "재미, 즐거움, 장난"}
    ],
    "G단어": [
        {word: "game", meaning: "놀이, 게임, 시합"}, {word: "garden", meaning: "정원"}, 
        {word: "gas", meaning: "휘발유, 기름"}, {word: "gate", meaning: "문, 출입문"}, 
        {word: "gentle", meaning: "온화한, 상냥한"}, {word: "get", meaning: "~을 얻다, ~을 사다"}, 
        {word: "give", meaning: "~을 주다"}, {word: "glad", meaning: "즐거운, 기쁜, 기꺼이~하다"}, 
        {word: "glass", meaning: "유리, 잔"}, {word: "go", meaning: "가다"}, 
        {word: "god", meaning: "신"}, {word: "good", meaning: "착한, 좋은"}, 
        {word: "grandma", meaning: "할머니"}, {word: "grass", meaning: "풀, 잔디"}, 
        {word: "great", meaning: "큰, 거대한, 웅장한, 재미있는, 신나는"}, {word: "ground", meaning: "땅, 지면"}, 
        {word: "group", meaning: "모임, 집단, 무리"}, {word: "grow", meaning: "자라다, 성장하다, ~이 되다"}, 
        {word: "guitar", meaning: "기타"}
    ],
    "H단어": [
        {word: "half", meaning: "반, 절반"}, {word: "hall", meaning: "공회당, 회관, 현관, 복도"}, 
        {word: "handle", meaning: "~을 다루다, 처리하다, 손잡이"}, {word: "handsome", meaning: "잘생긴"}, 
        {word: "happen", meaning: "(사건이)일어나다, 발생하다"}, {word: "happy", meaning: "행복한"}, 
        {word: "hard", meaning: "어려운, 단단한, 열심히"}, {word: "hate", meaning: "미워하다, 싫어하다"}, 
        {word: "have", meaning: "가지다, 가지고 있다, ~하다"}, {word: "he", meaning: "그가, 그는"}, 
        {word: "hear", meaning: "~이 들리다, ~을 듣다"}, {word: "heavy", meaning: "무거운"}, 
        {word: "hello", meaning: "(가벼운 인사)안녕"}, {word: "help", meaning: "~을 돕다"}, 
        {word: "here", meaning: "여기에서, 여기에"}, {word: "hi", meaning: "안녕"}, 
        {word: "hide", meaning: "숨다"}, {word: "high", meaning: "높은, 높이, 높게"}, 
        {word: "hiking", meaning: "하이킹, 도보여행"}, {word: "hill", meaning: "언덕"}, 
        {word: "hit", meaning: "~을 치다, 때리다"}, {word: "hold", meaning: "~을 들다, 잡다, 쥐다"}, 
        {word: "hole", meaning: "구멍"}, {word: "holiday", meaning: "공휴일, 휴일"}, 
        {word: "hope", meaning: "희망, 기대, ~을 바라다, 희망하다"}, {word: "hose", meaning: "호스"}, 
        {word: "hospital", meaning: "병원"}, {word: "hot", meaning: "뜨거운, 더운"}, 
        {word: "hotel", meaning: "호텔"}, {word: "hour", meaning: "시간"}, 
        {word: "how", meaning: "어떻게, 어느 정도, 얼마만큼"}, {word: "hundred", meaning: "백, 백의"}, 
        {word: "hungry", meaning: "배고픈, 굶주린"}, {word: "hurry", meaning: "서두르다, 급한 상태"}, 
        {word: "hurt", meaning: "아프다, 다치다, 마음에 상처를 입다"}
    ],
    "I단어": [
        {word: "ice", meaning: "얼음, 빙판"}, {word: "idea", meaning: "생각"}, 
        {word: "if", meaning: "만일~라면"}, {word: "ill", meaning: "병든, 건강이 나쁜"}, 
        {word: "in", meaning: "~안에(서)"}, {word: "ink", meaning: "잉크"}, 
        {word: "interest", meaning: "관심, 흥미"}, {word: "into", meaning: "~안으로, ~속으로"}, 
        {word: "introduce", meaning: "~를 소개하다"}, {word: "island", meaning: "섬"}, 
        {word: "it", meaning: "그것, 날씨를 나타낼 때, 사람을 나타낼 때"}
    ],
    "J단어": [
        {word: "jet", meaning: "제트기"}, {word: "job", meaning: "일, 직업"}, 
        {word: "join", meaning: "~참가하다"}, {word: "jump", meaning: "뛰다, 뛰어오르다"}, 
        {word: "jungle", meaning: "밀림, 정글"}, {word: "just", meaning: "바로, 금방, 조금 전에"}
    ],
    "K단어": [
        {word: "keep", meaning: "~을 지니다, 가지다"}, {word: "key", meaning: "열쇠"}, 
        {word: "kick", meaning: "차다"}, {word: "kill", meaning: "죽이다, (시간을) 보내다"}, 
        {word: "kind", meaning: "종류, 친절한"}, {word: "king", meaning: "왕, 임금"}, 
        {word: "knock", meaning: "(문을)두드리다, 노크하다"}, {word: "know", meaning: "~를 알다"}
    ],
    "L단어": [
        {word: "lake", meaning: "호수"}, {word: "land", meaning: "육지, 땅"}, 
        {word: "large", meaning: "큰, 커다란"}, {word: "last", meaning: "마지막의, 최후의, 지난, 앞선"}, 
        {word: "late", meaning: "늦은"}, {word: "laugh", meaning: "웃다"}, 
        {word: "lead", meaning: "이끌다, 안내하다"}, {word: "leaf", meaning: "나뭇잎, 잎사귀"}, 
        {word: "leave", meaning: "떠나다, 작별하다"}, {word: "left", meaning: "왼쪽, leave의 과거.과거 분사형"}, 
        {word: "let", meaning: "~하게하다, ~시키다"}, {word: "letter", meaning: "글자, 편지"}, 
        {word: "lie", meaning: "거짓말, 눕다"}, {word: "light", meaning: "빛, 불을 붙이다, 가벼운"}, 
        {word: "like", meaning: "좋아하다, ~와 같은, ~와 닮은"}, {word: "line", meaning: "선, 줄"}, 
        {word: "list", meaning: "표, 목록"}, {word: "listen", meaning: "듣다, 귀를 기울이다"}, 
        {word: "long", meaning: "(물건의 길이가)긴, 길쭉한, (시간이)긴, 오랫동안"}, 
        {word: "look", meaning: "찾다, 보다, 바라보다"}, {word: "lose", meaning: "잃다, 지다, 패배하다"}, 
        {word: "lot", meaning: "많음, 다량"}, {word: "loud", meaning: "소리가 큰, 시끄러운"}, 
        {word: "love", meaning: "사랑하다, 아주 좋아하다, 사랑"}, {word: "low", meaning: "낮은"}, 
        {word: "luck", meaning: "운, 행운"}
    ],
    "M단어": [
        {word: "make", meaning: "~을 만들다"}, {word: "many", meaning: "많은, 다수의"}, 
        {word: "map", meaning: "지도"}, {word: "march", meaning: "행진하다"}, 
        {word: "market", meaning: "시장"}, {word: "marry", meaning: "결혼하다"}, 
        {word: "matter", meaning: "일, 사정, 상황, 중요하다, 문제가 되다"}, 
        {word: "may", meaning: "~해도 좋다(허락), ~일지도 모른다(추측)"}, 
        {word: "medal", meaning: "메달, 훈장"}, {word: "meet", meaning: "만나다"}, 
        {word: "meter", meaning: "(길이.거리의 측정 단위) 미터"}, {word: "middle", meaning: "중간, 중앙"}, 
        {word: "million", meaning: "백만"}, {word: "minute", meaning: "(시간의)분, 잠깐"}, 
        {word: "Miss", meaning: "~양, 미스~"}, {word: "model", meaning: "모델"}, 
        {word: "mom", meaning: "엄마"}, {word: "money", meaning: "돈"}, 
        {word: "month", meaning: "달, 개월"}, {word: "moon", meaning: "달"}, 
        {word: "morning", meaning: "아침, 오전"}, {word: "mountain", meaning: "산"}, 
        {word: "move", meaning: "움직이다"}, {word: "movie", meaning: "영화"}, 
        {word: "Mr.", meaning: "~씨, ~선생님"}, {word: "Mrs.", meaning: "~씨 부인, ~선생님"}, 
        {word: "much", meaning: "많은"}, {word: "music", meaning: "음악"}, 
        {word: "must", meaning: "~해야 한다, ~임에 틀림없다"}
    ],
    "N단어": [
        {word: "need", meaning: "~가 필요하다, ~을 필요로 하다"}, {word: "never", meaning: "결코~않다"}, 
        {word: "new", meaning: "새로운"}, {word: "news", meaning: "뉴스, 소식"}, 
        {word: "next", meaning: "(to와 함께) ~의 옆에, 다음의"}, {word: "nice", meaning: "좋은, 멋진, 친절한"}, 
        {word: "night", meaning: "밤"}, {word: "no", meaning: "(대답에서) 아니오, 하나도~없는"}, 
        {word: "noise", meaning: "소음, 소리"}, {word: "north", meaning: "북쪽"}, 
        {word: "not", meaning: "~아니다"}, {word: "now", meaning: "지금, 현재"}, 
        {word: "number", meaning: "수, 숫자"}, {word: "nurse", meaning: "간호사"}
    ],
    "O단어": [
        {word: "of", meaning: "~의, ~중에서, ~로 만든"}, {word: "off", meaning: "(옷.신발 등을) 벗고, 멀리, (전기.가스등을) 꺼 놓고"}, 
        {word: "office", meaning: "사무실"}, {word: "often", meaning: "흔히, 자주"}, 
        {word: "oh", meaning: "아, 아이구"}, {word: "oil", meaning: "기름, 유화, 유화물감"}, 
        {word: "OK", meaning: "좋아요, 됐어요"}, {word: "old", meaning: "낡은, 오래된, (나이가) ~살인, 늙은, 나이든"}, 
        {word: "on", meaning: "~위에"}, {word: "once", meaning: "이전에, 옛날에, 한번, 일단~하고 나면"}, 
        {word: "open", meaning: "~을 열다, 열려 있는"}, {word: "or", meaning: "또는, 혹은"}, 
        {word: "other", meaning: "다른, 그 밖의"}, {word: "out", meaning: "밖에, 밖으로"}, 
        {word: "over", meaning: "~위에, 끝난"}
    ],
    "P단어": [
        {word: "paint", meaning: "페인트, 페인트를 칠하다, 그림 그리다"}, {word: "pair", meaning: "한 쌍, 한 벌, 한 켤레"}, 
        {word: "pardon", meaning: "용서, 허락, ~를 용서하다, 봐주다"}, {word: "park", meaning: "공원, 유원지"}, 
        {word: "party", meaning: "파티, 모임"}, {word: "pass", meaning: "(시간이) 지나다, ~을 건네주다, (시험에) 합격하다"}, 
        {word: "pay", meaning: "(돈을) 지불하다"}, {word: "peace", meaning: "평화"}, 
        {word: "piano", meaning: "피아노"}, {word: "pick", meaning: "(꽃.과일 따위를) 꺾다, 따다"}, 
        {word: "picnic", meaning: "소풍, 피크닉"}, {word: "piece", meaning: "단편, 한 조각"}, 
        {word: "pilot", meaning: "조종사"}, {word: "pin", meaning: "핀"}, 
        {word: "pine", meaning: "솔, 소나무"}, {word: "pipe", meaning: "관, 파이프, 파이프 담배"}, 
        {word: "place", meaning: "장소, 곳"}, {word: "plan", meaning: "계획"}, 
        {word: "plane", meaning: "비행기"}, {word: "plant", meaning: "식물, ~을 심다"}, 
        {word: "play", meaning: "놀다, (운동 경기를)하다, 연주하다"}, 
        {word: "please", meaning: "제발, 미안하지만, ~를 기쁘게 하다"}, 
        {word: "point", meaning: "(뾰족한)끝, ~를 가리키다"}, {word: "police", meaning: "경찰"}, 
        {word: "pool", meaning: "수영장, 웅덩이"}, {word: "poor", meaning: "가난한"}, 
        {word: "post", meaning: "우편물을 부치다, 우편물"}, {word: "poster", meaning: "포스터"}, 
        {word: "potato", meaning: "감자"}, {word: "practice", meaning: "연습, 연습하다"}, 
        {word: "present", meaning: "현재, 참석한, 출석한, 선물"}, {word: "pretty", meaning: "예쁜, 귀여운"}, 
        {word: "print", meaning: "인쇄, 인쇄하다, 발행하다, (프린터에서)프린트하다"}, 
        {word: "problem", meaning: "문제"}, {word: "pull", meaning: "~을 끌다, 잡아당기다"}, 
        {word: "push", meaning: "~을 밀다"},         {word: "put", meaning: "~을 놓다, 두다"}
    ],
    "Q단어": [
        {word: "queen", meaning: "왕비, 여왕"}, {word: "question", meaning: "물음, 질문"}, 
        {word: "quick", meaning: "빠른"}, {word: "quiet", meaning: "조용한, 고요한"}
    ],
    "R단어": [
        {word: "radio", meaning: "라디오"}, {word: "rain", meaning: "비, 비가 오다"}, 
        {word: "ready", meaning: "준비된"}, {word: "real", meaning: "진짜의, 정말의"}, 
        {word: "record", meaning: "기록, 기록하다"}, {word: "remember", meaning: "기억하다"}, 
        {word: "repeat", meaning: "되풀이하다, 반복하다"}, {word: "rest", meaning: "휴식, 잠, 쉬다, 휴식하다"}, 
        {word: "restaurant", meaning: "식당, 음식점"}, 
        {word: "return", meaning: "~로 돌아가다, 돌아오다, ~을 돌려주다, 반납하다"}, 
        {word: "ribbon", meaning: "리본, 장식용 띠"}, {word: "rich", meaning: "돈 많은, 부자의"}, 
        {word: "ride", meaning: "타다, (자동차를)태워 주기"}, {word: "right", meaning: "오른쪽, 옳은"}, 
        {word: "ring", meaning: "반지, (종.벨이)울리다, (종.벨을)치다"}, {word: "river", meaning: "강"}, 
        {word: "road", meaning: "길, 도로"}, {word: "robot", meaning: "로봇"}, 
        {word: "rock", meaning: "바위, 작은 돌"}, {word: "rocket", meaning: "로켓"}, 
        {word: "roll", meaning: "~를 굴리다, 구르다"}, {word: "roof", meaning: "지붕"}, 
        {word: "rose", meaning: "장미, rise의 과거형"}, {word: "round", meaning: "둥근, 원형의"}, 
        {word: "run", meaning: "달리다, 작동하다, 움직이다"}
    ],
    "S단어": [
        {word: "same", meaning: "같은 것, 같은, 똑같은"}, {word: "sand", meaning: "모래"}, 
        {word: "say", meaning: "말하다"}, {word: "scissors", meaning: "가위"}, 
        {word: "score", meaning: "점수, 득점"}, {word: "sea", meaning: "바다"}, 
        {word: "season", meaning: "계절"}, {word: "seat", meaning: "자리, 좌석"}, 
        {word: "see", meaning: "보다"}, {word: "sell", meaning: "~을 팔다"}, 
        {word: "send", meaning: "~을 보내다"}, {word: "service", meaning: "서비스, 손님 시중, 예배, 교통편, 군대"}, 
        {word: "set", meaning: "~을 두다, 놓다, (시간.장소.가격 등을)정하다, (해. 달이)지다, (기구의)한 벌, 세트"}, 
        {word: "shall", meaning: "~하겠다, ~할까요"}, {word: "shape", meaning: "모양"}, 
        {word: "she", meaning: "그녀는, 그녀가"}, {word: "sheet", meaning: "종이, (침대의)시트"}, 
        {word: "ship", meaning: "배"}, {word: "shoot", meaning: "쏘다, 발사하다, (카메라를)누르다"}, 
        {word: "shop", meaning: "상점, 가계, 장을 보다, 물건을 사다"}, 
        {word: "short", meaning: "(길이.거리.시간이) 짧은, (키가)작은"}, 
        {word: "shout", meaning: "외치다, 소리치다"}, {word: "show", meaning: "보여주다, 구경거리, 쇼, 전시회"}, 
        {word: "shower", meaning: "소나기, 샤워, (일종의)파티"}, {word: "shut", meaning: "~을 닫다, 잠그다"}, 
        {word: "sick", meaning: "병든, 병난"}, {word: "side", meaning: "옆, 측면, 쪽"}, 
        {word: "sight", meaning: "시력, 언뜻 보기, 풍경, 광경"}, {word: "sign", meaning: "표지, 기호, 표시"}, 
        {word: "sing", meaning: "노래하다"}, {word: "sir", meaning: "님, 귀하, 선생님(남성에 대한 경칭)"}, 
        {word: "sit", meaning: "앉다"}, {word: "size", meaning: "크기, 치수"}, 
        {word: "skate", meaning: "스케이트, 스케이트 타다"}, {word: "sky", meaning: "하늘"}, 
        {word: "sleep", meaning: "잠, 잠을 자다"}, {word: "slide", meaning: "미끄러지다"}, 
        {word: "slow", meaning: "느린"}, {word: "smell", meaning: "냄새"}, 
        {word: "smile", meaning: "미소"}, {word: "smoke", meaning: "연기, 담배 피우다"}, 
        {word: "snow", meaning: "눈, 눈이 내리다"}, {word: "so", meaning: "그렇게, 그와 같이, 몹시, 상당히"}, 
        {word: "soap", meaning: "비누"}, {word: "soccer", meaning: "축구"}, 
        {word: "soft", meaning: "조용한, 차분한, (날씨.기후 등이) 화창한, 따뜻한, 부드러운, 푹신푹신한"}, 
        {word: "some", meaning: "얼마간의, 약간의, 대략, ~쯤"}, {word: "song", meaning: "노래"}, 
        {word: "soon", meaning: "곧, 머지않아"}, {word: "sorry", meaning: "가엾은, 미안한, 죄송한"}, 
        {word: "sound", meaning: "소리, 음, ~인 것 같다, 건전한, 건강한"}, 
        {word: "south", meaning: "남쪽"}, {word: "space", meaning: "우주, 공간, 틈"}, 
        {word: "speak", meaning: "말하다"}, {word: "speed", meaning: "속도, 속력"}, 
        {word: "spell", meaning: "(철자를) 쓰다"}, {word: "spend", meaning: "(돈.시간을) 쓰다, 소비하다"}, 
        {word: "sport", meaning: "운동"}, {word: "spring", meaning: "봄"}, 
        {word: "square", meaning: "정사각형, (숫자의) 제곱, 광장"}, {word: "stair", meaning: "계단"}, 
        {word: "stamp", meaning: "우표"}, {word: "stand", meaning: "서다, 참다, 견디다"}, 
        {word: "star", meaning: "별, 인기인, 유명인사, (호텔이나 식당의) 등급 표시"}, 
        {word: "start", meaning: "출발하다, 떠나다, 시작하다"}, {word: "station", meaning: "정거장"}, 
        {word: "stay", meaning: "남다, 머무르다"}, {word: "steam", meaning: "증기"}, 
        {word: "step", meaning: "걸음, 스텝"}, {word: "stick", meaning: "막대기"}, 
        {word: "stone", meaning: "돌"}, {word: "stop", meaning: "멈추다, 정류장"}, 
        {word: "store", meaning: "가게, 상점, ~을 저장하다, 쌓아 두다"}, {word: "storm", meaning: "폭풍우"}, 
        {word: "story", meaning: "이야기"}, {word: "stove", meaning: "난로, 화덕"}, 
        {word: "straight", meaning: "곧은, 똑바른, 곧장"}, {word: "strange", meaning: "이상한"}, 
        {word: "street", meaning: "거리, 길"}, {word: "strike", meaning: "~을 치다, 때리다, ~을 두들기다, 파업"}, 
        {word: "strong", meaning: "힘센, 강한, 단단한, 유능한"}, 
        {word: "stupid", meaning: "어리석은, 바보 같은"}, {word: "subway", meaning: "지하철"}, 
        {word: "summer", meaning: "여름"}, {word: "sun", meaning: "태양, 해"}, 
        {word: "supermarket", meaning: "슈퍼마켓"}, {word: "sure", meaning: "~을 확신하는"}, 
        {word: "surprise", meaning: "놀람, 놀라운 일, 놀라게 하다, ~에 놀라다"}, 
        {word: "sweet", meaning: "달콤한, 맛있는"}, {word: "swim", meaning: "헤엄치다, 수영하다"}, 
        {word: "swing", meaning: "그네, 흔들리다"}, {word: "switch", meaning: "스위치, ~을 바꾸다"}
    ],
    "T단어": [
        {word: "table", meaning: "식탁, 테이블, 표, 목록"}, 
        {word: "take", meaning: "가져가다, 데려가다, ~을 쥐다, ~을 먹다, 마시다"}, 
        {word: "talk", meaning: "말하다, 이야기하다"}, {word: "tall", meaning: "키가 큰"}, 
        {word: "tape", meaning: "(테이프로) ~을 붙이다, 접착용 테이프, 녹음용 테이프"}, 
        {word: "taste", meaning: "~을 맛보다, 먹어보다, 맛이 나다, 맛"}, {word: "taxi", meaning: "택시"}, 
        {word: "teach", meaning: "가르치다"}, {word: "team", meaning: "팀, 조"}, 
        {word: "telephone", meaning: "전화기"}, {word: "television", meaning: "텔레비전"}, 
        {word: "tell", meaning: "말하다, 이야기하다"}, {word: "temple", meaning: "사원, 신전"}, 
        {word: "tennis", meaning: "정구, 테니스"}, {word: "than", meaning: "~보다"}, 
        {word: "thank", meaning: "~에게 고맙다고 하다"}, {word: "that", meaning: "저것, 그것, 저~, 그~"}, 
        {word: "the", meaning: "그~, 저~, 유일한 사물.대상을 나타낼 때"}, 
        {word: "then", meaning: "그때, 그 다음에"}, 
        {word: "there", meaning: "그 곳에, 거기에, (be동사와 함께)~이 있다"}, 
        {word: "they", meaning: "그들, 그것들"}, {word: "thick", meaning: "두꺼운"}, 
        {word: "thin", meaning: "얇은, 가느다란, 마른"}, {word: "thing", meaning: "물건"}, 
        {word: "think", meaning: "생각하다"}, {word: "thirsty", meaning: "목마른"}, 
        {word: "this", meaning: "이~, 이사람, 이것"}, {word: "thousand", meaning: "천(1,000), 천의"}, 
        {word: "through", meaning: "~을 꿰뚫어, ~을 통과하여"}, {word: "throw", meaning: "던지다, 내던지다"}, 
        {word: "thunder", meaning: "천둥"}, {word: "ticket", meaning: "표, 티켓"}, 
        {word: "till", meaning: "~할 때까지, ~까지"}, {word: "time", meaning: "시간, 시각, 곱하기, ~배, ~번"}, 
        {word: "tired", meaning: "피곤한, 지친, 싫증난, 질린"}, {word: "to", meaning: "~에, ~로, ~에게"}, 
        {word: "today", meaning: "오늘"}, {word: "together", meaning: "함께, 같이"}, 
        {word: "tomorrow", meaning: "내일"}, {word: "tonight", meaning: "오늘 밤"}, 
        {word: "too", meaning: "또한, 역시, 너무, 지나치게"}, {word: "top", meaning: "꼭대기, 한껏, 최고"}, 
        {word: "touch", meaning: "(손으로)만지다, ~에 대다"}, {word: "town", meaning: "소도시"}, 
        {word: "train", meaning: "기차"}, {word: "travel", meaning: "여행하다"}, 
        {word: "tree", meaning: "나무"}, {word: "trip", meaning: "여행"}, 
        {word: "truck", meaning: "트럭"}, {word: "true", meaning: "진실의, 정말인"}, 
        {word: "try", meaning: "~을 해보다, 시도하다, 노력하다"}, {word: "tulip", meaning: "튤립"}, 
        {word: "turn", meaning: "돌다, ~을 돌리다"}, {word: "twice", meaning: "두 번, 2회"}
    ],
    "U단어": [
        {word: "umbrella", meaning: "우산"}, {word: "under", meaning: "~의 밑에, (나이,가격이)~아래인, ~한 상태인"}, 
        {word: "understand", meaning: "이해하다, 알아듣다"}, {word: "until", meaning: "~까지"}, 
        {word: "up", meaning: "위로, 위쪽으로"}, {word: "use", meaning: "~을 사용하다, 쓰다"}, 
        {word: "usual", meaning: "늘 하는, 흔히 있는"}
    ],
    "V단어": [
        {word: "vacation", meaning: "방학, 휴가"}, {word: "very", meaning: "아주, 대단히"}, 
        {word: "video", meaning: "비디오"}, {word: "village", meaning: "마을"}, 
        {word: "violin", meaning: "바이올린"}, {word: "visit", meaning: "방문하다"}
    ],
    "W단어": [
        {word: "wait", meaning: "기다리다"}, {word: "wake", meaning: "잠이 깨다, ~을 깨우다"}, 
        {word: "walk", meaning: "걷기, 산책, 걷다"}, {word: "want", meaning: "~을 원하다, ~하고 싶다"}, 
        {word: "war", meaning: "전쟁"}, {word: "warm", meaning: "따뜻한"}, 
        {word: "wash", meaning: "~을 씻다"}, {word: "waste", meaning: "낭비하다"}, 
        {word: "watch", meaning: "지켜보다, 구경하다, 손목시계"}, {word: "way", meaning: "길, 도로, 방법, 방식"}, 
        {word: "we", meaning: "우리"}, {word: "weak", meaning: "약한, 힘없는, 허약한"}, 
        {word: "wear", meaning: "(옷을)입다"}, {word: "weather", meaning: "날씨, 기후"}, 
        {word: "week", meaning: "주, 1주일"}, {word: "welcome", meaning: "환영하다"}, 
        {word: "well", meaning: "잘, 훌륭하게"}, {word: "west", meaning: "서쪽"}, 
        {word: "wet", meaning: "젖은"}, {word: "what", meaning: "무엇, 무슨"}, 
        {word: "when", meaning: "~할 때, 언제"}, {word: "where", meaning: "~곳, 어디에"}, 
        {word: "which", meaning: "어느 것, 어느~"}, {word: "who", meaning: "누구"}, 
        {word: "why", meaning: "왜, 어째서"}, {word: "wide", meaning: "폭이 넓은"}, 
        {word: "will", meaning: "~일 것이다, ~하겠다"}, {word: "win", meaning: "이기다"}, 
        {word: "wind", meaning: "바람, ~을 감다"}, {word: "wing", meaning: "(새.곤충 등의) 날개"}, 
        {word: "winter", meaning: "겨울"}, {word: "with", meaning: "~와 함께, ~으로, ~을 써서"}, 
        {word: "wonder", meaning: "놀랄 만한 일, 궁금해 하다"}, {word: "wood", meaning: "목재, 재목"}, 
        {word: "work", meaning: "일, 일하다, 근무하다, 직장, 사무실"}, {word: "world", meaning: "세계, 세상"}, 
        {word: "write", meaning: "쓰다"}, {word: "wrong", meaning: "나쁜, 잘못된, 틀린"}
    ],
    "X,Y,Z단어": [
        {word: "xmas", meaning: "Christmas의 축약형"}, {word: "xylophone", meaning: "실로폰"}, 
        {word: "yeah", meaning: "네"}, {word: "year", meaning: "해, 년, (나이) ~살"}, 
        {word: "yes", meaning: "네, 그렇습니다"}, {word: "yesterday", meaning: "어제"}, 
        {word: "yet", meaning: "아직, 벌써"}, {word: "you", meaning: "너, 너희들, 당신(들), (일반적으로)사람들"}, 
        {word: "young", meaning: "젊은, 어린"}, {word: "zero", meaning: "영(0), 영의"}, 
        {word: "zoo", meaning: "동물원"}
    ]
};

// 기존 방식과 호환성을 위한 전체 단어 배열
const englishWords = Object.values(wordGroups).flat();